[package]
name = "locker"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rsa = "0.6.0"
rand = "0.8.4"
aes-gcm-siv = "0.10.3"
minparse = "0.1.2"